### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by b-fett** [capriza/node-proxying-agent#10]
```
Error: Can't set headers after they are sent.
    at validateHeader (_http_outgoing.js:491:11)
    at Proxy.setHeader (_http_outgoing.js:498:3)
    at ProxyingAgent.startProxying (C:\Users\localpc\project\node_modules\proxying-agent\lib\proxying-agent.js:159:11)
    at Proxy.<anonymous> (C:\Users\localpc\project\node_modules\proxying-agent\lib\proxying-agent.js:218:10)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at Socket.socketOnData (_http_client.js:440:20)
```
while trying to connect ISA proxy server using `request` (same result with `http.request`).

versions:

| proxying-agent 	| 2.2.1        	|
|----------------	|--------------	|
| request        	| 2.87.0       	|
| node           	| 8.12.0       	|
| npm            	| 6.4.1        	|
| ISA            	| 5.0.5723.493 	|

code example:

```js
const Agent = require('proxying-agent');
const request = require('request');

...

request(
  {
    method: 'POST',
    url,
    body,
    json: true,
    agent: Agent.create(
      {
        proxy: `http://${user}:${password}@${host}:${port}`,
        authType: 'ntlm',
        ntlm: {
          domain,
        },
      },
      '',
    ),
  },
  (err, res) => {
    console.log(err, res);
  },
);
```

**Comment by fujifish** [comment]
Did you follow the instruction at https://github.com/capriza/node-proxying-agent#ntlm-authentication?

**Comment by b-fett** [comment]
Yes, at first i get error `Error: NTLM failed. Socket closed prematurely`. After addtion 
```diff
180d181
>   ntlmOptions.headers['Connection'] = 'keep-alive';
```
error disappeared and now request with type 3 message header gets response code 407 and headers
```
Proxy-Authenticate: Negotiate
Proxy-Authenticate: Kerberos
Proxy-Authenticate: NTLM
```
I'm testing proxy with curl command
```
$ curl --proxy-ntlm --proxy http://host:port --proxy-user user:password http://test.net
```
and it works

**Comment by fujifish** [comment]
Is the target server (not the proxy) you're trying to access http or https?

**Comment by b-fett** [comment]
it's http

**Comment by fujifish** [comment]
Do you mind trying to access an https target (any target will do)? Also add "tunnel: true" to the agent creation options and let me know the results.

**Comment by b-fett** [comment]
if i'm trying make request with https and https agent i get `Error: Tunnel creation failed. Received status code 407` and `Proxy-Authenticate`: `Negotiate, Kerberos, NTLM`; i suspect issues with challenges.

**Comment by fujifish** [comment]
Are you using the latest version (released a couple of days ago)? There was a bug in a previous version that could sometimes cause the agent to use the incorrect socket after the NTLM handshake. 

After you upgrade, can you share the wireshark capture for both a successful request and for a failed attempt so I can compare?

**Comment by b-fett** [comment]
with latest `2.2.4` version i get 
```
Error: socket hang up
    at createHangUpError (_http_client.js:331:15)
    at Socket.socketCloseListener (_http_client.js:363:23)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at TCP._handle.close [as _onclose] (net.js:561:12)
```

**Comment by fujifish** [comment]
Thanks. Can you share a wireshark capture for both a successful request through curl and for a failed attempt through proxying-agent so I can compare the packets NTLM messages?

**Comment by b-fett** [comment]
here are wireshark detailed logs without some sensitive data.
now connection with message3 opens with same local port as initial connection, but no response backs and error appears.
[success.log](https://github.com/capriza/node-proxying-agent/files/2452322/success.log)
[fail.log](https://github.com/capriza/node-proxying-agent/files/2452323/fail.log)

**Comment by fujifish** [comment]
I can see in the failed run that the request is missing the keep alive header.
Can you please try to add the `keepAlive: true` option to the agent creation options and test again?
If it still fails please attach the wireshark log again.

**Comment by fujifish** [comment]
Have you made any progress with this?

**Comment by b-fett** [comment]
@fujifish i had corporate environment where i could test library. but unfortunately i haven't it now.
however i tried your suggestion and it didn't work.
