### ISSUE TITLE
Error: did not receive NTLM type 2 message

### ISSUE THREAD

**Issue by Obirah** [capriza/node-proxying-agent#12]
Hi,

this more of a question than an issue. When trying to use NTLM auth, I get the following error:

`events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: did not receive NTLM type 2 message
    at HttpsProxyingAgent.ProxyingAgent.emitError (/Users/myuser/Softwareentwicklung/Repositories/js-proxy-test/node_modules/proxying-agent/lib/proxying-agent.js:306:37)
    at HttpsProxyingAgent.<anonymous> (/Users/myuser/Softwareentwicklung/Repositories/js-proxy-test/node_modules/proxying-agent/lib/proxying-agent.js:190:12)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at ClientRequest.EventEmitter.emit (domain.js:442:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:555:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:441:20)
    at Socket.emit (events.js:182:13)
    at Socket.EventEmitter.emit (domain.js:442:20)
Emitted 'error' event at:
    at HttpsProxyingAgent.ProxyingAgent.emitError (/Users/myuser/Softwareentwicklung/Repositories/js-proxy-test/node_modules/proxying-agent/lib/proxying-agent.js:306:23)
    at HttpsProxyingAgent.<anonymous> (/Users/myuser/Softwareentwicklung/Repositories/js-proxy-test/node_modules/proxying-agent/lib/proxying-agent.js:190:12)
    [... lines matching original stack trace ...]
    at Socket.EventEmitter.emit (domain.js:442:20)`

My proxy server definitely uses NTLMv2, via CNTLM I can easily connect with it using NTLMv2 auth.

My JavaScript test code looks as follows:

`const proxyOptions = {
        proxy: 'http://my-credentials-as-base-64@my.company.proxy.domain.de:8080',
        authType: 'ntlm',
        ntlm: {
            domain: 'DOMAIN'
        }
    };
    const proxyingAgent = require('proxying-agent').globalize(proxyOptions);

    const opts = {
        host: 'ec2.amazonaws.com',
        port: 443,
        agent: proxyingAgent
    };

    const req = https.get(opts, function(response) {
        console.log(response.statusCode);
        console.log(response.headers);

        response.on('data', function(data) {
           console.log(data.toString());
        });
    });

    req.on('socket', function(socket) {
        req.write('DATA');
        req.end();
    });`

I anonymized all personal and company information. For the credentials in the proxy URL I tried different approaches:
- username:password as base64 encoded string
- DOMAIN\username:password as base64 encoded string

Can you give me a hint what I'm doing wrong?

**Comment by fujifish** [comment]
When using `globalize` there is no need to set the `agent` in the request options (since the agent is used globally), so first try to removing that and run again.
If it still doesn't work I'd be happy to jump on a screen sharing session to debug.

**Comment by Obirah** [comment]
Sorry, forgot to remove that, because I also tried it with the non-globalize variant (same result). I removed the agent from the request options now, but nothing changes.

I'd love to have a screen sharing session, but unfortunately that's not gonna be compliant with my company's privacy policies. :(

**Comment by dteeter** [comment]
When working with a squid server running NTLM authentication, I was able to get past the "did not receive NTLM type 2 message" error by adding these headers in proxying-agent.js after line 180: 

ntlmOptions.headers['Proxy-Connection']='keep-alive';
ntlmOptions.headers['keep-alive']='true';

**Comment by fujifish** [comment]
@dteeter would you mind jumping on a screen sharing session to debug?

**Comment by fujifish** [comment]
I've release version 2.3.0 with the suggested solution by @dteeter.
I no longer have access to a proxy with ntlm auth so I can't test it works.
Do you mind checking it and letting me know?

**Comment by dteeter** [comment]
Hi Navdav,

Thanks! I’ll give it a try on Monday.

-Dan

**Comment by fujifish** [comment]
@dteeter did you have a chance to check?

**Comment by allisont** [comment]
@dteeter - Were you able to get this working ?. I'm still seeing a socket hangup error with the latest version, any help would be highly appreciated.
