### ISSUE TITLE
socket hangup error (ECONNRESET)

### ISSUE THREAD

**Issue by allisont** [capriza/node-proxying-agent#14]
Hi, 

Wonder if you could shed some light on the issue I'm running into where I get the socket hangup error:

Made the following changes to the library code to allow for null domain:
1. Commented out the following code in proxying-agent.js starting on line 26.
`
/*
    if (!this.options.ntlm || !this.options.ntlm.domain) {
      throw new Error('NTLM domain must be provided');
    }*/
`

2. Modified code in ntlm.js as below:
`
function createType1Message(options){
  var domain = '';
  if(options.domain && options.domain.length > 0) {
    domain = escape(options.domain.toUpperCase());
  }
`<br/>
`
function createType3Message(msg2, options) { <br/>
... 
  if(options.domain && options.domain.length > 0) {
    domainName = escape(options.domain.toUpperCase());
  }
`
HTTP_PROXY environment set as such:
http://username:password@10.x.x.x:8080/

Below is the options object passed to the globalize function:
`
var proxyOptions = {
            proxy: process.env.HTTP_PROXY,
            authType: 'ntlm',
            ntlm: {
              domain: null //Made changes to library code to ignore domain
            }
        };
       require('proxying-agent').globalize(proxyOptions);
         let req = https.get({host: options.host, port: options.port, timeout: 60000}, callback);

`
where options.host: **gmail.com** and port: **443**. I've tried some other hosts as well but they all fail.

        req.on('socket', function(socket) {
            this.logger.info(`Got socket response`);
            req.write('DATA');
            req.end();
        });

        req.on('response', (response) =>  {
            this.logger.info(`Got response, ${response.toString()}`);
            if (response.statusCode !== 200) {
                let err = new Error('Unable to get successful response: ' + [response.statusCode]);
                return callback(err);
            }        
        });

        req.on('finish', () => {
            this.logger.info(`finish`);
            callback();
        });

        req.on('error', (err) => { 
            this.logger.info(`request error ${err}`);
            callback(err); 
        });

`
Added some log statements to the proxying-agent.js (startProxying method) to dump the values being passed:

**tunnelOptions** : {"path":"gmail.com:443","tunnel":true,"ntlm":{"domain":null,"workstation":"myDesktop","username":"username","password":"password"},"authType":"ntlm","proxy":{"protocol":"http:","slashes":true,"auth":"username:password","host":"10.x.x.x:8080","port":"8080","hostname":"10.x.x.x","hash":null,"search":null,"query":null,"pathname":"/","path":"/","href":"http://username:password@10.x.x.x:8080/"},"ssl":false,"host":"10.x.x.x","port":"8080","method":"CONNECT","hostname":"10.x.x.x","headers":{}}
**tunnelOptions headers**: {"Proxy-Authorization":"NTLM _base64 encoded string_","Proxy-Connection":"Keep-Alive"}

**And this is the exception I get:**
The 'error' handler in the _startProxying_ method gets invoked first followed by the 'close' handler. I do not see the 'connect' handler getting invoked at all.

Tunnel creation failed. Socket error: code- ECONNRESET, Error: socket hang up
    at createHangUpError (_http_client.js:330:15)
    at Socket.socketCloseListener (_http_client.js:362:23)
    at Socket.emit (events.js:164:20)
    at TCP._handle.close [as _onclose] (net.js:568:12), JSON: {"code":"ECONNRESET"}

I've also gotten a wireshark trace and as far as I can tell the connection is established with the proxy but soon thereafter the connection gets reset. All I see is the [RST] ACK from my client machine. 

Also I do not see the 'socket' or 'connect' handlers being invoked.

Would really appreciate any help you can offer, I've trying to debug this issue for a couple of days now and running out of things to try.

Also if possible could you please share a simple working example of the code containing the GET and POST calls.

**Comment by allisont** [comment]
Note that in the above scenario the proxy is HTTP & the server is HTTPS

**Comment by fujifish** [comment]
Unfortunately I no longer have access to an environment with an NTLM proxy so there is little I can do to check issues.
If you like, I can try to find some time to debug with you in a shared session. Would that work?

**Comment by allisont** [comment]
@fujifish, what would I need to have a shared session ?. If there is any logs I can collect please let me know. I've tried to capture a Wireshark before and can do it again first thing tomorrow morning.
