### ISSUE TITLE
Exception when an https request is made and proxy agent is configured (Node version <=8.x )

### ISSUE THREAD

**Issue by roieu** [capriza/node-proxying-agent#9]
Using node version v8.11.1
1. Configured a global proxy (pointing to [Burb sniffer](https://portswigger.net/burp))
`require('proxying-agent').globalize('http://127.0.0.1:8080');`
2. Created an HTTPS request 
3. Got the following exception

> Error: Protocol "https:" not supported. Expected "http:"
    at new ClientRequest (_http_client.js:131:11)
    at request (http.js:38:10)
    at Object.http.request (/Users/roieuziel/dev/new-capriza/connectors/mocky-invoice/node_modules/proxying-agent/lib/proxying-agent.js:380:16)
    at request (https.js:239:15)
    at Object.https.request (/Users/roieuziel/dev/new-capriza/connectors/mocky-invoice/node_modules/proxying-agent/lib/proxying-agent.js:394:16)
    at RedirectableRequest._performRequest (/Users/roieuziel/dev/new-capriza/connectors/mocky-invoice/node_modules/follow-redirects/index.js:128:24)
    at new RedirectableRequest (/Users/roieuziel/dev/new-capriza/connectors/mocky-invoice/node_modules/follow-redirects/index.js:54:8)
    at Object.wrappedProtocol.request (/Users/roieuziel/dev/new-capriza/connectors/mocky-invoice/node_modules/follow-redirects/index.js:252:14)
    at dispatchHttpRequest (/Users/roieuziel/dev/new-capriza/connectors/mocky-invoice/node_modules/axios/lib/adapters/http.js:132:25)
    at new Promise (<anonymous>)

This does not happen with latest node version (v9.2.0)

**Comment by roieu** [comment]
@ycarmel can also reproduce this issue :-)

**Comment by fujifish** [comment]
@roieu Are you doing `require('https')` or `require('http')` for making the http request?

**Comment by roieu** [comment]
I am using axios
